### PR TITLE
Volume control (continued from #65)

### PR DESCRIPTION
**Pull request by NickHu**
Conflicts resolved and brought up to date with master.

### CODE REVIEW

**Comment by travitch** [comment]
Thanks.  I don't know if there are any non-Linux users, but do you think it would be possible to only conditionally enable this module on Linux (given the ALSA dependency)?

**Comment by NickHu** [comment]
I have no idea I'm afraid, and I don't have any systems running other operating systems to test.
A quick googling seems to suggest that cabal can condition on operating systems - if you added that into the cabal file I wouldn't object.

**Comment by IvanMalison** [comment]
@NickHu Can you handle the merge conflicts?

**Comment by NickHu** [comment]
Done

**Pull request merged**
