### PR TITLE
Added a new battery format for showing charging status

### PR DESCRIPTION
**Pull request by abdulsattar**
It shows "On" for charging and shows the percentage otherwise. Made it the
default.

### CODE REVIEW

**Comment by silasdavis** [comment]
Would be really nice to see this, any comments? Very useful to see if your laptop is actually plugged in or not.

**Comment by abdulsattar** [comment]
The problem with this is, it uses polling to know the status. It'd be great if we could handle an event to know the status. I don't really know how to do that.

**Comment by travitch** [comment]
One possibility would be to listen for the 'changed' signal in the UPower DBus API.  Whenever the state changes, you could read the 'OnBattery' property.  The interplay with suspend/resume might be annoying, but UPower claims to send those signals, too.

http://upower.freedesktop.org/docs/UPower.html

**Comment by sakshamsharma** [comment]
This PR has been superseded by #147 , although we can probably borrow ideas from this into the code, now that we have a handler for state.

**Pull request closed without merging**
