### PR TITLE
Make battery bar more informative.

### PR DESCRIPTION
**Pull request by sakshamsharma**
Had sent this long back. Had been closed since I renamed the branch.
Adds time-remaining and charging/discharging/completed status.

### CODE REVIEW

**Comment by sakshamsharma** [comment]
@travitch @IvanMalison Can you suggest a better way to do this? At the moment I have to do:
```
cat /sys/class/power_supply/BAT1/status
```
to see the battery. Not something I enjoy. I'm sure adding this feature to master would be a good idea.

**Comment by IvanMalison** [comment]
I can't say that I know much about querying battery status but I have to say that that seems very not portable.

**Comment by IvanMalison** [comment]
@sakshamsharma Can you handle merge conflicts?

**Comment by sakshamsharma** [comment]
Right. had forgotten about this.
Will do soon. I had moved to Nix, where taffybar with GTK3 isn't working somehow, and haven't found the time to debug that.

**Comment by sakshamsharma** [comment]
@IvanMalison I have rebased this PR with the current master, and have tested this code on my system.

My battery widget creation call in taffybar.hs is as follows:
```haskell
batt  = batteryBarNewWithFormat defaultBatteryConfig "$percentage$% ($time$) - $status$" 30
```

There should be no breaking changes, or even usability changes. Also, a particular doc-string's first line had been removed 2 years ago, put it back :smile:

BTW should we also document this new constructor somewhere?

**Comment by IvanMalison** [comment]
> n removed 2 years ago, put it back 
> 
> BTW should we also document this new constructor somewhere?

changelog maybe

**Comment by sakshamsharma** [comment]
Makes sense. Any other issues with this?

Is the unicode character usage okay? It won't be enabled unless the user chooses to.
I would probably like it better if we can pass a configuration flag (boolean) to toggle unicode characters. But that can be done in another PR.

**Comment by IvanMalison** [comment]
> Is the unicode character usage okay? It won't be enabled unless the user chooses to.
> I would probably like it better if we can pass a configuration flag (boolean) to toggle unicode characters. But that can be done in another PR.

The other option would be a function that takes state to markup or something liike that.

**Comment by IvanMalison** [comment]
@sakshamsharma We can iterate it on it in further pull requests. This looks good for now.

**Comment by sakshamsharma** [comment]
Sounds good. Yaay for a new release! Thanks for all your work.

**Pull request merged**
