### PR TITLE
Safer X11, Faster Icon Performance

### LINKED ISSUE #105: Crash when multiple windows close simultaneously
Hi there,

Taffybar crashes with [my configuration](http://hub.darcs.net/ertes/config/browse/mytaffybar) when two windows are destroyed simultaneously. This is how I can reproduce it:
- Run: urxvt -e screen -S test
- Run: urxvt -e screen -x test
- In one of those windows exit the shell.

This causes the screen session to end and both windows to close at the same time. Taffybar goes with them, resulting in the following error:

```
% mytaffybar
Monitor 0 is not available in the selected screen
The program 'mytaffybar' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 12 error_code 3 request_code 20 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

I don't mind restarting Taffybar as nothing really depends on it, but I close multiple windows at the same time very often (browser windows, a set of pictures, Gimp windows, etc.).

### LINKED ISSUE #191: Icon Performance is really bad with certain icons
Spotify and Atom are both examples of icons that have very bad performance. Their performance is so bad because they don't provide low resolution icons, and because we currently use (linked) lists to represent them in memory. They need to remain contiguous in memory from the point where they are fetched from x11

### PR DESCRIPTION
**Pull request by IvanMalison**
I finally figured #105 out! Unfortunately it took custom bindings to a few xlib calls, and our own dedicated x11 event loop to do it...

We'll want to monitor xmonad/X11#51 to see if what they end up coming up with there is suitable for our needs. Theres a lot of work to be done there though, so I don't think waiting for their solution is a viable option, especially since this fixes the single most annoying outstanding bug in taffybar.

Because I ended up writing our own bindings to getProp I also made it so that the icon code doesn't use haskell lists anymore, which DRASTICALLY improves icon performance. This pretty much 100% resolves #191 for me. For anyone wondering how bad things WERE try running spotify with icons on before this change and you'll see that there is massive lag whenever that icon needs to be displayed or updated.

I don't have my hopes too high, but this could also have an impact on #228, since so many things were changed. 

IMPORTANT: I actually can't guarantee that this change fixes #105 for workspace switcher, you'll have to switch to WorkspaceHUD if you want to be assured that this is fix. That said, it should just be a matter of running all x11 calls through the dedicated thread. I know that @teleshoes has strong feelings about this, but I really think that we should consider deprecating WSS at this point.

### CODE REVIEW

**Comment by simlu** [comment]
Omg, I'm so excited for this! I can finally get rid of my auto-restart script!

**Comment by IvanMalison** [comment]
> Omg, I'm so excited for this! I can finally get rid of my auto-restart script!

Awesome

@simlu Do you have a consistent repro/are you able to install from source to verify that this does, indeed fix the issue for you?

I have to admit that while I mostly think I understand what is going on, there are one or two details that are a little hazy for me right now, and I want to make sure that this works for others before declaring the issue resolved.

**Comment by simlu** [comment]
I won't be able to do any testing until later this month unfortunately. Have you tried running my script that I posed in #105?

I use VMs and can test from source, but usually revert afterwards since I dislike having those various dependencies installed.

**Comment by IvanMalison** [comment]
@simlu Oh no! It looks like it is SOMETIMES able to handle your script and sometimes not. Pretty weird, right? If I reduce the number of windows involved it's a lot more consistent. I think that maybe I missed a spot that normally runs very quickly, or perhaps it has to do with window switcher.

The good news is that it does log that it encounters an error before dying. I'm so bummed though. I'm going to look in to it a bit more though.

**Comment by travitch** [comment]
Thanks for looking at this.  My read of this is that there were roughly two issues:
 * Some functions from the X11 wrapper can throw exceptions that weren't being caught and were killing threads
 * While we seem to mostly do an okay job with single-threaded access to GTK, we didn't do so well with raw X11 functions and were doing thread-unsafe things with X11

Do we basically need to audit everything we have in the X11 monad?  Should we look at a solution that prevents this more thoroughly and perhaps remove all unsafe functions?

**Comment by simlu** [comment]
@IvanMalison Is there any change in the amount of crashes using my config? I've rewritten a bunch of code that did unsafe access. Did you try stripping the bar config to an absolute minimum?

Also what is the error that is being logged?

@travitch This is what I did with my config basically (I think). I'm curious if that plus the changes @IvanMalison made potentially fixes it.

**Comment by IvanMalison** [comment]
> Some functions from the X11 wrapper can throw exceptions that weren't being caught and were killing threads

Not exactly. A few things conspired to cause #105

- `xGetWindowProperty` and other X11 funtions were marked as unsafe which meant that anything interrupting BACK to haskell would cause the entire runtime to be frozen. [This post](https://www.reddit.com/r/haskell/comments/1vsw1z/how_to_work_around_blocking_in_an_unsafe_ffi_call/cew18mv/) explains it well if you are curious.
- We weren't properly setting an X11Error handler (which is very different than catching errors in haskell), so when an error occurred it would crash the program.
- Previously, when I tried properly setting an X11Error handler, it would fail because the provided X11 handler was a function in the haskell runtime (which is why the first issue mentioned is important)
- Less significant, but still a hurdle that I had to overcome in this pull request: A lot of X11 calls were actually being made on the UI thread for Gtk in a blocking way which was bad because that can cause the UI thread to hang

@travitch @simlu
The key point here is that most of these exceptions CANT be caught in any way in haskell, especially with how the FFI was configed. The solution to the main problem was to BOTH set a handler AND mark the FFI calls as safe. This caused an issue with X11 requests and threads, which is why I made a dedicated thread to handle all X11 requests.

> While we seem to mostly do an okay job with single-threaded access to GTK, we didn't do so well with raw X11 functions and were doing thread-unsafe things with X11

Yes, although, in theory, X11 should be usuable from different threads when XInitThreads is called. For whatever reason, when I marked the X11 functions as safe, I started getting a bunch of errors about unknown request, even though we DO initialize the threading system of X11, which should (in theory) allow for calls to X11 from different threads.

> Do we basically need to audit everything we have in the X11 monad?

Yes, possibly, although currently, at least with the things touched by my own configuration, I think I've been able to stamp out all of these. Also, it is possible to call in to X11 without using that monad, and we do in some places, IIRC.

> Should we look at a solution that prevents this more thoroughly and perhaps remove all unsafe functions?

That's basically what I've done, although I just realized that I missed getGeometry, which is very likely the cause of the remaining issues that I am seeing.

**Comment by IvanMalison** [comment]
Great news! It turns out that the reason there were still some crashes WAS that `getGeometry` was not safe!

@simlu 
> @IvanMalison Is there any change in the amount of crashes using my config?

Yes. I am actually now able to run your script and avoid a crash every time.

> I've rewritten a bunch of code that did unsafe access. Did you try stripping the bar config to an absolute minimum?

It seems like you mostly just added `catchAny` in a whole bunch of places. As I mentioned [above](https://github.com/travitch/taffybar/pull/229#issuecomment-336615532), the exceptions from Xlib can't be caught in Haskell, so I don't think that any of the rewrites that you've done are doing anything, unfortunately.

> I'm curious if that plus the changes @IvanMalison made potentially fixes it.

I think that the issue is 100% fixed assuming that the only widget you are using is WorkspaceHUD. I'm going to look at the others in a little bit, but I'd love it if you could validate that running just WorkspaceHUD can handle the issue.

**Comment by IvanMalison** [comment]
@simlu @travitch Here's a gif of the new code handling @simlu's script from #105

**Comment by teleshoes** [comment]
@IvanMalison woo, nice stuff man!

if this DOES fix 228, i would absolutely agree with deprecating WSS. WSHUD is easier to use and extend, has more features, and is more flexible; if only WSHUD didnt crash all the time for me.

i used WSHUD for the past week, and it crashed at least twice a day every workday.

i have switched to 229 (plus cherry-picked 208+209 on top). ill let you know after a few workdays go by how 228 stands.

**Comment by IvanMalison** [comment]
@teleshoes If you do get crashes, can you check whether they are due to #231, and then see if you ALSO get the issues in WSS when applying this PR?

I'm a little bit worried that I may have caused a double free somewhere with the refactors to the icon image code.

**Comment by teleshoes** [comment]
will do, though im pretty sure ive never seen that exact crash before

**Comment by travitch** [comment]
It sounds like this is a significant improvement over what we had before, so I'm going to go ahead and merge it.  We can fix any issues that pop up over the next week, hopefully.  If it looks stable for a week, I'll go ahead and cut a release.

**Comment by IvanMalison** [comment]
@travitch Awesome. Things have been pretty stable for me so far, but I do want to monitor #231 just to make sure that it isn't something that was introduced by this change.

Great news about cutting a release! I think We're at a good point for doing something like that!

**Pull request merged**
