### PR TITLE
Handle cases where a config dir exists but the menu file in it does not

### PR DESCRIPTION
**Pull request by benley**
Don't give up after checking the first one; continue down the list of
possible paths until we find a menu file that exists.

More fixes for #240

### CODE REVIEW

**Comment by benley** [comment]
@u11gh here's my attempt at further fixing #240 and #241.  I'm still pretty new to haskell so hopefully the change makes sense.

**Comment by IvanMalison** [comment]
You need to import <$> to make this compile in 7.8, although I have already done that in the relevant file with my changes...

**Comment by benley** [comment]
I'll try to redo this atop your changes now that I have a working version :-)

**Comment by benley** [comment]
OK, please take another look.  I'm not aware of a good way to properly cherrypick your cleanups from #237 using git to preserve authorship, but I did at least port the changes over in a standalone commit so the diffs are coherent.

**Pull request merged**
