### PR TITLE
Build with GHC 8

### PR DESCRIPTION
**Pull request by sakshamsharma**
Please test build with `cabal` before merging. I don't use it anymore.
Although I suppose it should build fine.

Also, since the build had stopped working thanks to [this issue](https://github.com/gtk2hs/gtk2hs/issues/179#issuecomment-255053104), I have added the required package to the cabal file. Seems to build on my system ATM, need more people to confirm.

Lastly, I've added some comments on installation in the README.md as well. Please refer to the issue linked above for details.

### CODE REVIEW

**Comment by sakshamsharma** [comment]
I advanced the head to stack LTS 8.1, and fixed the dependency issues. Symlinking `stack.yaml` to `stack-8.0.yaml` should work alright. @travitch please upstream.

**Comment by sakshamsharma** [comment]
@travitch since you were reviewing, mind having a look at this too? I've fixed the merge conflict.

**Comment by travitch** [comment]
I have to figure out why travis is completely failing on this branch

**Comment by IvanMalison** [comment]
@sakshamsharma You need to change the ghc compiler version.

**Comment by sakshamsharma** [comment]
I suppose it should be fixed now. There was something I don't remember doing, or maybe I accidentally pushed it. I've undone it now.

**Comment by IvanMalison** [comment]
@sakshamsharma Still need to change the environment variable that specifies the ghc version to 8.0.2

**Pull request merged**
